spring:
  datasource:
        names: root,reader
        root:
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://localhost:3306/biColor
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
        reader:
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://localhost:3306/biColor
          username: reader
          password: reader
          driver-class-name: com.mysql.jdbc.Driver

druid:
  filters: stat


## Mybatis
mybatis:
    typeAliasesPackage: sample.dto
    mapperLocations: classpath:mapper/*.xml


example:
  service:
    enabled: true
    prefix: 1111
    suffix: 2222