base:
    name: test

server:
    port: 9090
    jsp-servlet:
      class-name: org.apache.jasper.servlet.JspServlet

## dataSource
spring:
  application:
    name: schedule
  datasource:
    url: jdbc:mysql://192.168.1.211:3306/test_quartz
    username: root
    password: testsql123
    driver-class-name: com.mysql.jdbc.Driver

## Mybatis
mybatis:
    typeAliasesPackage: sample
    mapperLocations: classpath:mapper/*.xml
