base:
    name: test

server:
    port: 9090

cache:
    prefix: boot
    expire: 300

## dataSource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/biColor
    name: biColor
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
## Mybatis
mybatis:
    typeAliasesPackage: sample.dto
    mapperLocations: classpath:mapper/*.xml


